Update design memo.

diff --git a/DESIGN_MEMO b/DESIGN_MEMO
--- a/DESIGN_MEMO
+++ b/DESIGN_MEMO
@@ -1,37 +1,44 @@
------------------------------- list-style(old) ------------------------------
 
-        <name>            <installed>   <stowed>   <source>
- Gauche-0.8.14                     -          O          O
- Gauche-0.9                        O          O          O
- bash-4.0                          -          O          O
- bash-4.1                          O          O          O
- mosh-0.2.0                        -          -          O
- ruby-1.8.7-p174                   -          O          O
- ruby-1.9.1-p376                   -          O          O
- ruby-1.9.2-preview1               O          O          O
- simstring-1.0                     -          -          O
- subversion-16                     -          -          O
- tinyscheme1.39                    -          -          O
- tokyocabinet-1.4.42               O          O          O
- wget-1.11.4                       O          O          O
-
------------------------------- tree-style(new) ------------------------------
+------------------------------ display info ------------------------------
 
 
-        <name>            <installed>   <stowed>   <source>
+        <name>            <enabled>   <installed>
  Gauche
-   1. Gauche-0.8.14               -          O          O
-   2. Gauche-0.9                  O          O          O
+   1. Gauche-0.8.14               -          O
+   2. Gauche-0.9                  O          O
  bash
-   3. bash-4.0                    -          O          O
-   4. bash-4.1                    O          O          O
+   3. bash-4.0                    -          O
+   4. bash-4.1                    O          O
  mosh
-   5. mosh-0.2.0                  -          -          O
+   5. mosh-0.2.0                  -          -
  ruby
-   6. ruby-1.8.7-p174             -          O          O
-   7. ruby-1.9.1-p376             -          O          O
-   8. ruby-1.9.2-preview1         O          O          O
+   6. ruby-1.8.7-p174             -          O
+   7. ruby-1.9.1-p376             -          O
+   8. ruby-1.9.2-preview1         O          O
 
 > ss 7
   => stow -D 8(ruby-1.9.2-preview1) && stow -R 7(ruby-1.9.1-p376)
+
+------------------------------ specfile    ------------------------------
+
+example of ruby-2.1.3
+
+;;-*- mode: scheme; syntax: scheme -*-;;
+(define-stowspec '(
+ (conf . "if [ ! -e ./configure ] ; then
+  echo 'Error: stowspec supports ./configure script included tar ball only, sorry...'
+  exit 1
+fi
+command='./configure --prefix=/usr/local/stow/ruby-2.1.3' 
+echo \" \" ============================================================
+echo \" \" [[ ${command} ]]
+echo \" \" ============================================================
+${command}
+")
+ (make . "make")
+ (install . "make install")
+ (arc . "ruby-2.1.3.tar.gz")
+ (url . "http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.3.tar.gz")
+ (projname . "ruby-2.1.3")
+))
 
